import sqlite3
from pathlib import Path


def generate_overview(conn: sqlite3.Connection, root: Path) -> str:
    total_symbols = conn.execute("SELECT COUNT(*) FROM symbols WHERE is_test=0").fetchone()[0]
    total_files = conn.execute("SELECT COUNT(*) FROM files").fetchone()[0]
    total_edges = conn.execute("SELECT COUNT(*) FROM edges").fetchone()[0]

    # Top modules by symbol count
    module_rows = conn.execute(
        """
        SELECT file_path, COUNT(*) as cnt
        FROM symbols WHERE is_test=0
        GROUP BY file_path ORDER BY cnt DESC LIMIT 10
        """
    ).fetchall()

    # Key classes
    class_rows = conn.execute(
        "SELECT name FROM symbols WHERE kind='class' AND is_test=0 LIMIT 10"
    ).fetchall()

    # Key functions (top by caller count)
    func_rows = conn.execute(
        """
        SELECT s.name, COUNT(e.caller_id) as callers
        FROM symbols s
        LEFT JOIN edges e ON e.callee_id = s.id
        WHERE s.kind IN ('function','method') AND s.is_test=0
        GROUP BY s.id ORDER BY callers DESC LIMIT 10
        """
    ).fetchall()

    lines = [
        "# Project Overview",
        "",
        f"**{total_symbols} symbols** across {total_files} files · {total_edges} call edges",
        "",
        "## Top modules by symbol count",
    ]
    for row in module_rows:
        lines.append(f"- `{row[0]}` ({row[1]} symbols)")

    lines += ["", "## Key classes"]
    for row in class_rows:
        lines.append(f"- `{row[0]}`")

    lines += ["", "## Most-called functions"]
    for row in func_rows:
        lines.append(f"- `{row[0]}` ({row[1]} callers)")

    lines += ["", f"*Generated by sigil from `{root.name}`*"]
    return "\n".join(lines)


def write_overview(conn: sqlite3.Connection, root: Path) -> Path:
    out = root / ".sigil" / "overview.md"
    out.parent.mkdir(exist_ok=True)
    out.write_text(generate_overview(conn, root), encoding='utf-8')
    return out
